package StockMarket;


/**
* StockMarket/StockServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockMarket.idl
* Saturday, June 3, 2017 10:47:00 AM IST
*/

public interface StockServerOperations 
{
  float getStockValue (String symbol);
  String[] getStockSymbols ();
} // interface StockServerOperations
